spring:
  application:
    name: geo-localizacao
  data:
    redis:
      url: redis://${REDIS_HOST:localhost}:6379

server:
  port: 8080

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true