## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: fabricio211/geo-location
  VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        run: ./mvnw verify -B

      - name: Build container image
        run: |
          chmod +x ./mvnw
          ./mvnw package -Dquarkus.container-image.build=true 

      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: fabricio211
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish container image (latest)
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest